require 'fiddle/import'


module PonyScale
  extend Fiddle::Importer
  dlload '.build/release/libHello.dylib' # dylib generated by SPM
  extern 'double MAKW_test(double)' #
end
weight = PonyScale::MAKW_test(18) # Calculating weight by passing 18 as mass 
puts "Your pony weighs: #{weight}"